  location ~ @@APP_BASE_HREF[^/]+/q/ {
    deny all;
    return 404;
  }
  
  location @@APP_BASE_HREF {
    # try_files $uri $uri/$is_args$args =404;
    alias /usr/share/nginx/html/;
    try_files $uri $uri/ /index.html /index.html;
    
    sub_filter_once off;
    sub_filter 'base href="/"' 'base href="@@APP_BASE_HREF"';
    sub_filter </head> '<script language="javascript">@@INJECTED_ENV</script></head>';

    location ~ \.html$ {
      add_header X-Content-Type-Options "nosniff";
      add_header X-Frame-Options "SAMEORIGIN";
      add_header X-XSS-Protection "1; mode=block";
      add_header Cache-Control "private, no-cache, no-store, must-revalidate";
      add_header Expires "Sat, 01 Jan 2000 00:00:00 GMT";
      add_header Pragma no-cache;
    }

    location ~* \.mjs$ {
      types {
        text/javascript mjs;
      }
    }

    # cache all images and fonts for 1 month, as they should not change
    location ~* \.(?:jpg|jpeg|gif|png|ico|woff2)$ {
      expires 1M;
      add_header Cache-Control "public";

      set $cors_enabled @@CORS_ENABLED;
      set $cors_origin "";
      set $cors_cred "";
      set $cors_header "";
      set $cors_method "";
      set $cors_vary "";

      if ($cors_enabled = "true") {
        set $cors_origin $cors_origin_mapped;
        set $cors_cred   $cors_cred_mapped;
        set $cors_header $cors_header_mapped;
        set $cors_method $cors_method_mapped;
        set $cors_vary   $cors_vary_mapped;
      }

      add_header "Access-Control-Allow-Origin"      $cors_origin;
      add_header "Access-Control-Allow-Credentials" $cors_cred;
      add_header "Access-Control-Allow-Methods"     $cors_method;
      add_header "Access-Control-Allow-Headers"     $cors_header;
      add_header "Vary"                             $cors_vary;
    }

    # cache all webpack chunks for 1 month
    # this is safe, bacause on every change in code, the hash would change
    location ~* "\.(?:[a-f0-9]{10,})\.(js|css)$" {
      expires 1M;
      add_header Cache-Control "public";

      set $cors_enabled @@CORS_ENABLED;
      set $cors_origin "";
      set $cors_cred "";
      set $cors_header "";
      set $cors_method "";
      set $cors_vary "";

      if ($cors_enabled = "true") {
        set $cors_origin $cors_origin_mapped;
        set $cors_cred   $cors_cred_mapped;
        set $cors_header $cors_header_mapped;
        set $cors_method $cors_method_mapped;
        set $cors_vary   $cors_vary_mapped;
      }

      add_header "Access-Control-Allow-Origin"      $cors_origin;
      add_header "Access-Control-Allow-Credentials" $cors_cred;
      add_header "Access-Control-Allow-Methods"     $cors_method;
      add_header "Access-Control-Allow-Headers"     $cors_header;
      add_header "Vary"                             $cors_vary;
    }
  }
