name: Build Feature Branch

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
      - '!main'
      - '!fix/[0-9]+.[0-9]+.x'

jobs:
  docker:
    uses: onecx/ci-common/.github/workflows/docker-build.yml@v2test
    secrets: inherit
    with:
      platform: 'linux/amd64,linux/arm64'
      buildx: true
      push: false
      artifact: ''
      samoDockerFile: Dockerfile  